### ISSUE TITLE
Using datastore package via properties, skipping loadStruct

### ISSUE THREAD

**Issue by golangdaddy** [golang/appengine#110]
We would like to know if it is possible to modify the client libraries to be able to load and store property slices without having to load them into structs?

Is it possible to achieve this? As far as I know it is not possible to deploy hacked versions of the client libraries to App Engine?

Thanks

**Comment by astec** [comment]
You already can do this by implementing [PropertyLoadSaver](https://cloud.google.com/appengine/docs/standard/go/datastore/reference#hdr-The_PropertyLoadSaver_Interface) interface.

Or use [PropertyList](https://github.com/golang/appengine/blob/b79c28f0197795b4050bfcd7c4c2209136c594b1/datastore/prop.go#L83) class that already implements it.

P.S. probably this question is better suited for StackOverflow.
