### ISSUE TITLE
Add normal support for standart environment vendoring

### ISSUE THREAD

**Issue by anjmao** [golang/appengine#114]
Following app engine golang tutorial it is simply to run hello world app https://github.com/GoogleCloudPlatform/appengine-guestbook-go/tree/part1-helloworld 

main.go
```go
package hello

import (
    "fmt"
    "net/http"
)

func init() {
    http.HandleFunc("/", handler)
}

func handler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprint(w, "Hello, world!")
}
```

app.yaml
```
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
```

In hello world when I run `dev_appserver.py app.yaml` I'm getting service up and running. But If I add any vendor like golang echo and use `dep` to vendor app libraries then it is not building and I'm getting errors
```
Failed parsing input: parser: bad import "syscall" in vendor/golang.org/x/sys/unix/syscall_unix.go
```
This issue is also posted on https://stackoverflow.com/questions/39948027/how-do-i-make-vendoring-work-with-google-app-engine/40118834#40118834

I was able to run it using this approach https://github.com/nikolay-turpitko/x-gae-dep but it looks like a workaround. Is it possible to somehow run app locally and deploy it from my current GOPATH or I'm forced to adapt to google-cloud-sdk GOPATH?

**Comment by anjmao** [comment]
@broady From commits history I see that you are active contributor. Maybe you have any estimates or comments on this?

**Comment by agentmilindu** [comment]
@anjmao I'm having the same issue, cloud you find a clean solution than the workaround?
