### ISSUE TITLE
goapp gets ImportError: cannot import name goroots

### ISSUE THREAD

**Issue by sousk** [golang/appengine#124]
The same problem of https://github.com/golang/appengine/issues/74 seems to happen again with Cloud SDK version 190.0.1.

You'll get an error when you kick `goapp` command
```
Traceback (most recent call last):
  File "/path-to/google-cloud-sdk/platform/google_appengine/goapp", line 40, in <module>
    from google.appengine.tools import goroots
ImportError: cannot import name goroots
```

Now the workaround is a little bit different from the former one.
I could fix with that one liner bellow.
```
echo "GOROOTS = { 'go1.8': 'goroot-1.8', 'go1': 'goroot-1.8', 'go1.6': 'goroot-1.6'}" > /path-to/google-cloud-sdk/platform/google_appengine/google/appengine/tools/goroots.py
```

**Comment by sbuss** [comment]
`goapp` is not supported when run from the gcloud sdk. If you still must use it, please use the legacy SDK by going to https://cloud.google.com/appengine/docs/standard/go/download and clicking "Download and install the original App Engine SDK for Go."

**Comment by vvakame** [comment]
@sbuss I have a question. We can use `dev_appserver.py` instead of `goapp serve`, but I can't find way to alternative of `goapp test`. What's the right way for using GAE/Go?
