### ISSUE TITLE
datastore: invalid datastore.Property_Meaning: ENTITY_PROTO

### ISSUE THREAD

**Issue by sbuss** [golang/appengine#140]
The generated protobuf files in this project have their `proto.RegisterEnum` calls [stripped](https://github.com/golang/appengine/blob/b1f26356af11148e710935ed1ac8a7f5702c7612/internal/regen.sh#L33-L40) due to https://code.google.com/p/googleappengine/issues/detail?id=11670#c17. This was necessary because we still support `import appengine`, which is (mostly) a clone of this repo, which defines all of the same protos. So two packages both registering enums with the same names causes a panic.

Due to https://github.com/golang/protobuf/issues/484 we must change the datastore tests to use `MarshalTextString` instead of [`string(Marshal())`](https://github.com/golang/appengine/blob/b1f26356af11148e710935ed1ac8a7f5702c7612/datastore/load_test.go#L268-L284). Unfortunately, now that we're parsing strings, not having the enums registered breaks one of the tests with the error `invalid datastore.Property_Meaning: ENTITY_PROTO`.

We need to revert remove the logic to string the `RegisterEnum` calls and regenerate the protos.

In a local testing branch with those changes I have been unable to reproduce the [original panic](https://code.google.com/p/googleappengine/issues/detail?id=11670#c17). I'm unsure if that means this is safe to do, or if there is a case where the panic still occurs. This ticket will attempt to collect evidence that this is a safe change to make.

**Comment by sbuss** [comment]
CC @dsymonds (for the original changes) and @broady

**Comment by dsymonds** [comment]
It looks like those protos haven't been regenerated in a while. That alone has potential for some trouble. I suggest regenerating them alone (keeping the `RegisterEnum` stripping), pushing that change out, and letting that soak while you work on removing that. That'll also shrink the diff here.

**Comment by sbuss** [comment]
Good suggestion, @dsymonds, and thanks for taking a look! I broke it into #142, and I'll rebase and recreate #141 once that's merged.

**Comment by sbuss** [comment]
The change to protobuf which surfaced this issue will likely be reverted, so I am not actively working on fixing this until https://github.com/golang/protobuf/issues/622 is settled.

**Comment by sbuss** [comment]
This is kind of fixed via https://github.com/golang/protobuf/pull/628 -- though technically the same underlying issue exists but we just don't hit that code path.
