### ISSUE TITLE
datastore: []byte() cannot be saved or loaded if it contains invalid UTF-8 bytes

### ISSUE THREAD

**Issue by sbuss** [golang/appengine#143]
Replaces #136 

golang/protobuf#499 changed how the protobuf library handles strings: they are now expected to be valid UTF-8 strings. We have been [serializing structs by casting `[]byte` to `string`](https://github.com/golang/appengine/blob/b1f26356af11148e710935ed1ac8a7f5702c7612/datastore/save.go#L282-L287), which is now invalid.

@egag reported a related issue in #136, and this underlying issue surfaced from the investigation there.

This issue can be reproduced with this test:

```go
package main

import (
	"testing"

	"google.golang.org/appengine"
	"google.golang.org/appengine/aetest"
	"google.golang.org/appengine/datastore"
)

func TestPutBytes(t *testing.T) {
	inst, err := aetest.NewInstance(nil)
	if err != nil {
		panic(err.Error())
	}
	req, err := inst.NewRequest("GET", "/", nil)
	if err != nil {
		panic(err.Error())
	}
	ctx := appengine.NewContext(req)
	key := datastore.NewKey(ctx, "data", "data1", 0, nil)
	data := &struct{ Data []byte }{Data: []byte("\xa0\x01")} // Data: []byte("abc") works fine
	_, err = datastore.Put(ctx, key, data)
	if err != nil {
		t.Fatalf("testB: %v", err.Error())
	}
}
```

I think we need to add a `ByteValue` (or `BytesValue`?) to [datastore.PropertyValue](https://github.com/golang/appengine/blob/b1f26356af11148e710935ed1ac8a7f5702c7612/internal/datastore/datastore_v3.proto#L8)

**Comment by sbuss** [comment]
I am recommending that the protobuf team revert the changes to proto2. See https://github.com/golang/protobuf/issues/622

**Comment by egag** [comment]
@sbuss thank you for keeping this updated

**Comment by sbuss** [comment]
At this point it looks likely that the validation changes will be reverted, so I'm not actively working on a fix for this. As soon as there's a final decision from the protobuf team I will post another update.

**Comment by sbuss** [comment]
Fixed via https://github.com/golang/protobuf/pull/628
