### ISSUE TITLE
Request: Add a new tag for vgo

### ISSUE THREAD

**Issue by vvakame** [golang/appengine#145]
https://github.com/golang/go/wiki/vgo

https://github.com/golang/appengine/releases
This repository has a `v1.0.0` tag. but it is too old.
I think We should add a new (`v2.0.0`?) tag for package managers.
Currently, v1.0.0 is used automatically, which is very inconvenient. 😿

**Comment by broady** [comment]
If we tag with v2, we need to include it in the import path. `v1.1` should work, right?

/cc @tbpg @sbuss @rsc

**Comment by sbuss** [comment]
:+1: v1.1.0

**Comment by tbpg** [comment]
Agreed. That should unblock this issue and give a good "default" value in case users don't import `/v2` from the beginning.

**Comment by sbuss** [comment]
I'm going to do this tomorrow; I need a little time to get set up to gpg sign the tag.

**Comment by sbuss** [comment]
Fixed: https://github.com/golang/appengine/releases/tag/v1.1.0

Tag signed with my key: https://keybase.io/sbuss, https://keybase.io/sbuss/pgp_keys.asc?fingerprint=00ecc6c95fe71ea3a43af6706b5c4f4fe140917a

**Comment by tbpg** [comment]
Thanks!
