### ISSUE TITLE
Support for CloudSQL PostgreSQL on App Engine Standard

### ISSUE THREAD

**Issue by andybons** [golang/appengine#147]
Currently I’m using @broady’s https://github.com/broady/gae-postgres package, but it’s unclear whether it will break in the future since CloudSQL Postgres is not officially supported on App Engine Standard for Go (though to be honest I can’t find any documentation that states this).

**Comment by mattes** [comment]
ref: https://issuetracker.google.com/issues/67081578
ref: https://issuetracker.google.com/issues/35897413

From Google Cloud Support team:
> Please take note though, that Our App Engine Engineering Team is aware of this feature request and they are currently investigating it but with no ETA at this time

**Comment by sbuss** [comment]
I can confirm that Postgres will be supported in our next release of Go on App Engine (Go 1.11), using any standard Posgres sql driver.

**Comment by broady** [comment]
1.11 beta is released, postgres should just work™️ now.

Woohoo!

**Comment by gugahoi** [comment]
Still can't find any documentation wrt to this and the go runtime. Is this meant to be working? I can find sample code for the docs in the following languages: Python,Java,Node.js,C#, Ruby but no Go.
