### ISSUE TITLE
google.golang.org/appengine/log isn't compatible with GAE/Go 1.11

### ISSUE THREAD

**Issue by apstndb** [golang/appengine#163]
I am trying to migrate apps with App Engine API to Go 1.11 runtime for App Engine standard.
`google.golang.org/appengine/log` seems broken in Go 1.11 runtime because log loss is happen.

Example to reproduce

```go
package main

import (
	"google.golang.org/appengine"
	"google.golang.org/appengine/log"
	"net/http"
)

func main() {
	http.HandleFunc("/write_log_gae", func(w http.ResponseWriter, req *http.Request) {
		ctx := appengine.NewContext(req)
		log.Infof(ctx, "test")
		w.WriteHeader(http.StatusOK)
	})
	appengine.Main()
}
```

Single call of `/write_log_gae` emits three top level logs.
- request log in request
- log level prefixed line in stderr
- `internal.flushLog` RPC log in stderr

Frequently, RPC log says `Call error 3: invalid security ticket` and request log doesn't have apps log.

This screenshot is result of calling twice. The bottom half doesn't have app log(Severity is not set from child.)
![2018-10-17 13 37 56](https://user-images.githubusercontent.com/803393/47062693-6e811e00-d212-11e8-83d7-f1048d2f4aba.png)

**Comment by sbuss** [comment]
Can you confirm that you're using the latest version of this package: https://github.com/golang/appengine/releases/tag/v1.2.0?

**Comment by apstndb** [comment]
Yes, I am!

I am using go module and I have this `go.mod`.

```
module go111

require google.golang.org/appengine v1.2.0
```

**Comment by apstndb** [comment]
I have picked the log-security-ticket-fix branch by go module then deployed it!

```
$ go get google.golang.org/appengine@log-security-ticket-fix
```

It seems to be work correctly.
There are no `internal.flushLog` RPC log and log loss is not happened.

<img width="673" alt="2018-10-18 08 28 53" src="https://user-images.githubusercontent.com/803393/47122060-244e7a00-d2b0-11e8-82ca-d1b8e9926ebb.png">

**Comment by HazCod** [comment]
I have this issue once I deploy to AppEngine with package `v.1.4.0`. Any news on this?

**Comment by sbuss** [comment]
@HazCod This should be included in `1.4.0`. You're seeing the exact same behavior? Can you provide some more details, please?

**Comment by HazCod** [comment]
What details should you need? I see the “invalid security ticket”.

**Comment by jedruniu** [comment]
Still happening on go `1.12` and `google.golang.org/appengine v1.6.1`
