### ISSUE TITLE
datastore error - not an App Engine contex

### ISSUE THREAD

**Issue by cn007b** [golang/appengine#167]
I'm trying to upgrade my project from `go1` to `go111`.
In my project I'm using `datastore`, here you can see how my code looks:

````go
package controller

import (
	"google.golang.org/appengine/datastore"
	"log"
	"net/http"
	"time"
)

type Measurement struct {
	Project      string    `datastore:"project"`
	At           time.Time `datastore:"at"`
	Took         int       `datastore:"took,noindex"`
	ResponseCode int       `datastore:"responseCode"`
}

func MeasurementController(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	query := datastore.NewQuery("Measurement")
	data := make([]Measurement, 0)

	keys, err := query.GetAll(ctx, &data)
	if err != nil {
		log.Printf("Error %#v", err)
		return
	}

	log.Printf("Keys: %+v, Data: %+v", keys, data)
}
````
And I always get error: `Error: &errors.errorString{s:"not an App Engine context"}`
As you can see I've already replaced `ctx := appengine.NewContext(r)` to `ctx := r.Context()`
but it won't work.

**Comment by sbuss** [comment]
Can you verify that you've upgraded to the latest `google.golang.org/appengine` package?

**Comment by cn007b** [comment]
Yes, my `google.golang.org/appengine` version is `v1.2.0`.

**Comment by sinmetal** [comment]
Are you calling `appengine.Main()` ?

package main

import (
	"net/http"

	"google.golang.org/appengine"
)

func main() {
	http.HandleFunc("/", handler)

	appengine.Main()
}

https://cloud.google.com/appengine/docs/standard/go111/go-differences#writing_a_main_package

Only when appengine.Main() is executed, it injects appengine.Context into
request.
https://github.com/golang/appengine/blob/ae0ab99deb4dc413a2b4bd6c8bdd0eb67f1e4d06/internal/api.go#L93

2018年10月24日(水) 22:26 Johan Haals <notifications@github.com>:

**Comment by cn007b** [comment]
No, I don't.
Here, my `main.go`:
````go
func main() {
	routes.Init()

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	http.ListenAndServe(fmt.Sprintf(":%s", port), nil)
}
````

**Comment by cn007b** [comment]
I've put back `appengine.Main()` and now all works.
Thank you @sinmetal!
