### ISSUE TITLE
Problems installing goapp

### ISSUE THREAD

**Issue by samtstern** [golang/appengine#168]
I had a pretty rough installation experience.  This is on a brand new 2018 MacBook pro, I have not used any app engine tools on it before.

First I ran:
```
gcloud components install app-engine-go
```

Then I ran `goapp` ... command not found.  So I did:
```
chmod +x ~/google-cloud-sdk/platform/google_appengine/goapp
export PATH=$PATH:$HOME/google-cloud-sdk/platform/google_appengine
```
That got it on my path and executable.  Then running it:
```
$ goapp serve
Traceback (most recent call last):
  File "/Users/samstern/google-cloud-sdk/platform/google_appengine/goapp", line 136, in <module>
    goroot = GetGoRoot(os.environ['GOPATH'], sys.argv)
  File "/Users/samstern/google-cloud-sdk/platform/google_appengine/goapp", line 119, in GetGoRoot
    return os.path.join(SDK_BASE, goroots.GOROOTS[app_yaml.api_version])
KeyError: None
```

That's as far as I've got.  Stuck at this point.

**Comment by sbuss** [comment]
Glad you got it figured out!

We just released Go 1.11 on App Engine which no longer uses `goapp`. I recommend you use the new platform, it's much easier to use! https://cloud.google.com/appengine/docs/standard/go111/

**Comment by samtstern** [comment]
What about the equivalent of `goapp` serve @sbuss ?

**Comment by sbuss** [comment]
If you're using `google.golang.org/appengine` and want the local emulators, use `dev_appserver.py /path/to/app.yaml`. `dev_appserver.py` should be on your path when you install the app engine gcloud component. It has superseded all functionality of `goapp`

**Comment by BurntCaramel** [comment]
What is the equivalent of `goapp test`? How do you testing datastore locally?

**Comment by sbuss** [comment]
`go test` works normally as long as you are using a relatively up-to-date
gcloud and google.golang.org/appengine package.
