### ISSUE TITLE
all: better error message for "not an App Engine context"

### ISSUE THREAD

**Issue by broady** [golang/appengine#172]
Especially for Go 1.11, where `appengine.Main` isn't required, it's confusing when people try to use this package without `appengine.Main`.

Maybe we should modify the message to point to a doc explaining how to resolve the error, especially as it'll be much more common to see in Go 1.11+.

/cc @sbuss

**Comment by HazCod** [comment]
@broady: I come here since I'm victim to the same error.
How would one implement this correctly?
```
func main() {
	logger.Init(os.Stdout, os.Stdout, os.Stderr, os.Stderr)

	config, err := system.LoadConfig()
	if err != nil {
		logger.Error.Printf("Could not load config: %v", err)
	}

	listenAddr := fmt.Sprintf("%s:%d", config.ListeningHost, config.ListeningPort)
	err, router := system.NewRouter(listenAddr)
	if err != nil {
		logger.Error.Printf("could not create router: %v", err)
	}
	defer router.Close()

	router.SetPanicHandler(handlers.PanicHandler())

	db, err := system.GetDBInstance(
		config.ProjectID,
		config.DBInstance,
		config.DBName,
		config.DBUser,
		config.DBPassword,
	)
	if err != nil {
		logger.Error.Printf("could not connect to DB: %v", err)
	}
	defer db.Close()

	migrateDB(db)

	setupRoutes(router, db)

	language.Init()

	logger.Info.Println("Started listening on " + listenAddr)
	logger.Info.Println(router.Listen())
}

```

**Comment by mdempsky** [comment]
@broady Perhaps until this can be fixed properly, you (or someone) can roughly explain what this error means and how to handle it?

I just ran into this trying to use Go 1.11 on App Engine Standard, and I'm at a bit of a loss to understand it or how to proceed.

**Comment by broady** [comment]
Exactly right, @mdempsky.

That said, with the second generation beta runtime (go1.11), I believe it's technically possible to construct a valid App Engine context with just an *http.Request, without requiring use of appengine.Main.

**Comment by mdempsky** [comment]
> I believe it's technically possible to construct a valid App Engine context with just an *http.Request, without requiring use of appengine.Main.

I'm not sure if by technically possible you're referring to it's possible for (1) app developers to today use the classic client libraries without using appengine.Main, or that it's possible that (2) the classic client libraries could be modified to work without appengine.Main.

I don't think 1 is true. The only non-test function that creates an internal.context value appears to be internal.handleHTTP, which is only used by internal.Main (in turn used by appengine.Main).

I do think 2 is likely true though.

**Comment by emirhosseini** [comment]
@broady  I'm using 1.12 and getting this error so it seems that using appengine.Main is necessary.

**Comment by broady** [comment]
Yes, you must use appengine.Main if you want to use the packages under
google.golang.org/appengine.

You don't have to use those packages, though.
