### ISSUE TITLE
2 appengine packages?

### ISSUE THREAD

**Issue by alexisoyama** [golang/appengine#174]
It's not an issue but quite annoying. There are 2 appengine packages: "appengine" and  "google.golang.org/appengine". 

It seems like the doc is using this package as the official one. For ex. https://cloud.google.com/appengine/docs/standard/go/logs/reference

But when I download the SDK from https://cloud.google.com/appengine/docs/standard/go/download, it's a different package! 

And throws me an error. Why are there 2 packages? Which one should I use?

**Comment by alexisoyama** [comment]
In short, I'm asking

**Comment by sbuss** [comment]
You should use `google.golang.org/appengine`. The `appengine` package is deprecated, and is only present in App Engine Go 1.9 and prior.
