### ISSUE TITLE
Problem building Go 1.11 fatal error: libsecp256k1/include/secp256k1.h: No such file or directory

### ISSUE THREAD

**Issue by camstuart** [golang/appengine#175]
Hi,

I am having some difficulty deploying a GAE Standard (1.11 runtime) service that includes a package which I believe requires C compilation / build tooling (and based on this error, a specific C header file)

See `app.yaml`
```
runtime: go111
service: hodlclub-api
env_variables:
  INFURA_API_KEY: "xxx"
  GIN_MODE: release
  DSN: "user:pass@cloudsql(canwork-io:australia-southeast1:canwork-io)/hodl_club?parseTime=true"
handlers:
- url: /.*
  script: auto
```

I am able to `go build` locally without a problem. I suspect that one of my packages (`github.com/ethereum/go-ethereum/ethclient`) is the one reliant upon build tooling and header files. 
See cloud build output:

```
starting build "21ea6bd8-879c-42be-9f69-0829c2321691"

FETCHSOURCE
BUILD
Starting Step #0 - "fetcher"
Step #0 - "fetcher": Already have image (with digest): gcr.io/cloud-builders/gcs-fetcher
Step #0 - "fetcher": Fetching manifest gs://staging.canwork-io.appspot.com/ae/4eadde28-563b-4c9d-8305-59100d9d6e24/manifest.json.
Step #0 - "fetcher": Processing 1018 files.
Step #0 - "fetcher": ******************************************************
Step #0 - "fetcher": Status: SUCCESS
Step #0 - "fetcher": Started: 2018-11-19T12:43:21Z
Step #0 - "fetcher": Completed: 2018-11-19T12:43:22Z
Step #0 - "fetcher": Requested workers: 200
Step #0 - "fetcher": Actual workers: 200
Step #0 - "fetcher": Total files: 1018
Step #0 - "fetcher": Total retries: 0
Step #0 - "fetcher": GCS timeouts: 0
Step #0 - "fetcher": MiB downloaded: 11.69 MiB
Step #0 - "fetcher": MiB/s throughput: 13.61 MiB/s
Step #0 - "fetcher": Time for manifest: 109.10 ms
Step #0 - "fetcher": Total time: 0.98 s
Step #0 - "fetcher": ******************************************************
Finished Step #0 - "fetcher"
Starting Step #1 - "builder"
Step #1 - "builder": Pulling image: gcr.io/gae-runtimes/go111_app_builder:go111_1_11_2_20181111_RC00
Step #1 - "builder": go111_1_11_2_20181111_RC00: Pulling from gae-runtimes/go111_app_builder
Step #1 - "builder": Digest: sha256:51fb36bfa16e7013356867c3a3972986084df93e56258fc258579a5799f0436e
Step #1 - "builder": Status: Downloaded newer image for gcr.io/gae-runtimes/go111_app_builder:go111_1_11_2_20181111_RC00
Step #1 - "builder": 2018/11/19 12:43:24 Copying /workspace/_gopath/src/github.com to /tmp/staging382387556/srv/gopath/src/github.com
Step #1 - "builder": 2018/11/19 12:43:24 Copying /workspace/_gopath/src/gopkg.in to /tmp/staging382387556/srv/gopath/src/gopkg.in
Step #1 - "builder": 2018/11/19 12:43:24 Building from Go source in /tmp/staging382387556/srv/gopath/src/gitlab.com/canya-com/hodlclub/web-app-api, with main package at gitlab.com/canya-com/hodlclub/web-app-api
Step #1 - "builder": 2018/11/19 12:43:24 Building /tmp/staging382387556/srv/gopath/src/gitlab.com/canya-com/hodlclub/web-app-api, saving to /tmp/staging382387556/usr/local/bin/start
Step #1 - "builder": 2018/11/19 12:43:45 Wrote build output to /builder/outputs/output
Step #1 - "builder": 2018/11/19 12:43:45 Failed to build app: building app with command '[go build -o /tmp/staging382387556/usr/local/bin/start gitlab.com/canya-com/hodlclub/web-app-api]', env '[PATH=/go/bin:/usr/local/go/bin:/builder/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=ad82c49287c9 HOME=/builder/home BUILDER_OUTPUT=/builder/outputs DEBIAN_FRONTEND=noninteractive GOROOT=/usr/local/go/ GOPATH=/go GOPATH=/tmp/staging382387556/srv/gopath]': err=exit status 2, out=# github.com/ethereum/go-ethereum/crypto/secp256k1
Step #1 - "builder": srv/gopath/src/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:42:10: fatal error: libsecp256k1/include/secp256k1.h: No such file or directory
Step #1 - "builder": #include "libsecp256k1/include/secp256k1.h"
Step #1 - "builder": ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step #1 - "builder": compilation terminated.
Finished Step #1 - "builder"
ERROR
ERROR: build step 1 "gcr.io/gae-runtimes/go111_app_builder:go111_1_11_2_20181111_RC00" failed: exit status 1
```
I also attempted vendoring my packages with `dep` but that gave me strange `unknown network cloudsql` error when attempting the mysql (cloudsql) connection

**Comment by camstuart** [comment]
I have continued to try some further options to no avail;

1) Deploying as a GAE Flex runtime (By using a docker file)
2) And again after vendoring packages with `dep` and `vend`

In these situations, I can build and deploy. But my service fails to start with `unknown network cloudsql`

I'm using MySQL, and Services deployed with the earlier Go runtime use an identical DSN:

```
unable to connect to dsn: user:password@cloudsql(canwork-io:australia-southeast1:canwork-io)/hodl_club?parseTime=true with error: dial cloudsql: unknown network cloudsql"  
```

**Comment by sbuss** [comment]
> In these situations, I can build and deploy. But my service fails to start with unknown network cloudsql

If that's the error from Flex, then I believe that's expected. AFAIK flex doesn't have the special cloudsql database connection handler, you need to use the IP form.

As for libsecp256k1, I think we're just missing https://packages.debian.org/source/sid/libsecp256k1. I will try to get those headers included in our build images.

**Comment by camstuart** [comment]
I also found the solution to the missing cloudsql driver problem [over here](https://github.com/GoogleCloudPlatform/golang-samples/issues/692)

**Comment by camstuart** [comment]
@sbuss where you able to get those headers added? I'm still suffering on GAE Standard Go Runtime 1.11

**Comment by sbuss** [comment]
Unfortunately I haven't added the headers yet. There's an internal discussion on whether or not the ABI is stable enough for us to add this to our base image. Since we update the base image automatically, any breaking change to the ABI will break customers without warning. libsecp256k1 isn't the most stable lib and there's an open bug to determine exactly what the compatibility promise is.

**Comment by sbuss** [comment]
Looping back to this. I'm sorry to say that we don't have a way to provide this feature while ensuring our stability standards are met. You may want to check out [Google Cloud Run](https://cloud.google.com/run/) which is similar to App Engine but can run arbitrary containers, so you can add every system dependency you care about -- regardless of stability promises the dependency makes.

Sorry we couldn't do this! As an ethereum enthusiast myself, I feel your pain

**Comment by camstuart** [comment]
Understood! Thanks for the tip on cloud run. that must be new? I have a few use cases for it, so that's actually pretty cool
