### ISSUE TITLE
Go 1.11 runtime no longer set DATASTORE_PROJECT_ID environment variable

### ISSUE THREAD

**Issue by yegle** [golang/appengine#178]
https://godoc.org/cloud.google.com/go/datastore#NewClient suggest you can leave the second argument as empty string to use the current project, but it looks like the Go1.11 runtime no longer set the `DATASTORE_PROJECT_ID` environment variable.

I'm pretty sure this worked in Go1.11 runtime because I had to update app.yaml and add the environment variable when trying out the new runtime.

**Comment by broady** [comment]
You should use the `datastore.DetectProjectID` constant as the projectID argument. It's a sentinel value and the project ID will be detected based off the credentials. On the new App Engine runtime, that's from the metadata server. We will update the docs to make this clearer and to discourage use of empty string as a parameter.

I don't recall this environment variable being set in the App Engine environment, it comes from the datastore emulator.

If you have more questions, I suggest filing a bug in the https://github.com/googleapis/google-cloud-go repository.
