### ISSUE TITLE
delay.Func accepts multiple functions with the same name

### ISSUE THREAD

**Issue by eliasnaur** [golang/appengine#18]
Consider https://play.golang.org/p/yAsU5xx33L where the same name is used to register two delay functions. Using a simple app.yaml,

````
application: test
version: test
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
````

the app compiles and runs without error in the localhost server and in production. I believe attempts to register multiple functions under the same name should panic so the mistake is caught at initialization time. In particular because there is no way to directly test delay functions with aetest.

FWIW, I was hit by this today in production.

**Comment by layoaster** [comment]
What is the error message you get in production?

**Comment by eliasnaur** [comment]
I get no error, but I expected to. Accepted name clashes, the wrong delay.Func (might be) called in dev and in production. In my play.golang.org example, no error is raised, but either f or f2 could be called when a call is deserialized from the task queue. It probably depends on the order of delay.Func registration.

**Comment by okdave** [comment]
Seems like it would be pretty easy to fix by [checking the map](https://github.com/golang/appengine/blob/master/delay/delay.go#L127) before insertion, and setting `f.err` if the key is already used.

However, people might already be using this behaviour to overwrite previously-registered functions so it might be a regression in their eyes?

**Comment by okdave** [comment]
We could actually set `f.err` on the previously-set function, and so still support overwriting.

**Comment by zombiezen** [comment]
Happy to take this one (I don't have assignee ACLs).

**Comment by okdave** [comment]
@zombiezen You do now :)

**Comment by adamtanner** [comment]
I think @okdave's approach is fine.

Users should be aware that the key that is actually used in the map is based on the file that function is defined in** as well as the string that's passed to delay.Func. It's perfectly acceptable to reuse the same string if the delay.Func calls are in different files and they will not conflict.

** This actually caused me production issues in the past. Tasks will start failing if you move the delay.Func call during a refactoring and redeploy with tasks still in the queue.
