### ISSUE TITLE
Build flag "appengine" not set for submodules

### ISSUE THREAD

**Issue by akfaew** [golang/appengine#187]
Imagine an appengine environment:
```
main.go
submodule/submodule.go
```
When running this with `dev_appserver.py`, submodule.go will not have the "appengine" build flag set. This is a problem for me, because I import a library that uses `// +build appengine`.

**Comment by sbuss** [comment]
As said in https://github.com/golang/appengine/issues/187#issuecomment-455212424, this build tag is deprecated and is not set in Go 1.11 and beyond.
