### ISSUE TITLE
Datastore transaction put then get error

### ISSUE THREAD

**Issue by faisalraja** [golang/appengine#196]
When I do a put then a get in a transaction, I get a no such entity error. But doing the same thing outside a transaction I have no issues. I have also tried datastore.NewKey with specific string key, same result.

```
datastore.RunInTransaction(c, func(ctx context.Context) error {
  key := datastore.NewIncompleteKey(ctx, "Counter", nil)
  var x Counter
  var y Counter
  k2, err := datastore.Put(ctx, key, &x)
  if err := datastore.Get(ctx, k2, &y); err != nil {
  	// no such entity error
  }
  return nil
}, nil)
```

**Comment by sbuss** [comment]
This is expected behavior. From the [docs](https://cloud.google.com/datastore/docs/concepts/transactions#isolation_and_consistency):

> Unlike with most databases, queries and lookups inside a Datastore mode transaction do not see the results of previous writes inside that transaction. Specifically, if an entity is modified or deleted within a transaction, a query or lookup returns the original version of the entity as of the beginning of the transaction, or nothing if the entity did not exist then.
