### ISSUE TITLE
Unable to deploy due to sub-packages not being found

### ISSUE THREAD

**Issue by YannHulot** [golang/appengine#199]
```
(gcloud.app.deploy) Staging command [/Users/myname/google-cloud-sdk/platform/google_appengine/go-app-stager /Users/my_name/development/go_projects/github.com/c/app.yaml /Users/my_name/development/go_projects/github.com/my_project /var/folders/hp/3c8v4dfx1zn0t3k8g_7w5z782rdj3c/T/tmpyeaID7/tmpbDdacH] 
failed with return code [1].

------------------------------------ STDOUT ------------------------------------
building with dependencies from GOPATH
------------------------------------ STDERR ------------------------------------
2019/03/23 20:22:33 staging for go1.11
2019/03/23 20:22:33 Staging second-gen Standard app: failed analyzing /Users/my_name/development/go_projects/github.com/my_project: cannot find package "github.com/my_project/handlers" in any of:
	($GOROOT not set)
	/Users/my_name/development/go/src/github.com/my_project/handlers (from $GOPATH)
GOPATH: /Users/my_name/development/go
```

I am trying to deploy my application to gcloud using
```
gcloud app deploy
```

I have succesfully created my project and set the region.
I have confirmed that the application compiles correctly. 
Tests are all passing.

My app.yaml is very simple:
```
runtime: go111

handlers:
- url: /.*
  script: auto
```

I am using go version 1.11 with submodules so I am not working in my GOPATH.
It runs locally just fine with the command:
```
dev_appserver.py app.yaml
```

My directory structure is as is:

```
Project
 |
 +-- main.go
 +-- app.yaml
 +-- go.mod
 +-- go.sum
 |    
 +-- handlers
 |  |  
 |  +-- handlers.go
 |    
 +--  data
 |  |  
 |  +-- models.go
 |  
 |    
 +-- helpers
 |  |  
 +  |-- helpers.go
```
For brevity, i have not included all the sub-packages but you get the idea.
I am kind of at a loss about what to do here. 
I have succesfully deployed the example app from the tutorial and another small app which did not have any subpackages.

Is there something I am missing?

**Comment by YannHulot** [comment]
I have found the issue. 
When working with submodules, you need to unset the GOPATH from your shell. 
After unsetting the GOPATH, i was able to deploy the app to gcloud.

**Comment by paoloposso** [comment]
but how?
