### ISSUE TITLE
datastore entityGroupKind incorrect (?)

### ISSUE THREAD

**Issue by CaptainCodeman** [golang/appengine#20]
It doesn't appear to be used as far as I could tell but for when it is, it appears to be wrong (unless things are changing with the datastore behind the scenes)

https://github.com/golang/appengine/blob/12d5545dc1cfa6047a286d5e853841b6471f4c19/datastore/metadata.go#L14

In Python / NDB the EntityGroup has a middle underscore:

https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.ext.ndb.metadata#google.appengine.ext.ndb.metadata.EntityGroup

**Comment by okdave** [comment]
Thanks @CaptainCodeman 

I think I'll end up deleting it for now, since it's not used at all.
