### ISSUE TITLE
3rd party router w/ appengine.Main()

### ISSUE THREAD

**Issue by undeadindustries** [golang/appengine#200]
Is it possible to use 3rd party routers like denco, etc, with appengine.Main()?

This question was asked here:
https://github.com/golang/appengine/issues/185

But the answer was actually just using Go's default net/http.

It would be nice to just be able to do:  appengine.Main(router)

**Comment by mtraver** [comment]
Yes, that's possible. You do need to use `net/http` because `appengine.Main()` uses the default ServeMux, but only to instruct `net/http` to serve everything using your router of choice:

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/naoina/denco"
	"google.golang.org/appengine"
)

func index(w http.ResponseWriter, r *http.Request, params denco.Params) {
	fmt.Fprintf(w, "Welcome to Denco!\n")
}

func main() {
	mux := denco.NewMux()
	handler, err := mux.Build([]denco.Handler{
		mux.GET("/", index),
	})
	if err != nil {
		log.Fatal(err)
	}

	http.Handle("/", handler)
	appengine.Main()
}
```
