### ISSUE TITLE
Verify running in Standard AppEngine, not Flex

### ISSUE THREAD

**Issue by coryrc** [golang/appengine#220]
When someone tries to run this project in Flex, it gives very weird error messages. I'm thinking an easy fix is to confirm IsStandard() when appengine.Main() is called or fmt.Fatalf() right away? (but I don't really know)

**Comment by juliehockett** [comment]
Yes, you should be able to just call IsStandard() (or, conversely, IsFlex(), to determine if you're in a Flex environment).

**Comment by coryrc** [comment]
Would a PR to add the check to this project be accepted?

**Comment by broady** [comment]
What are the weird error messages? I'd rather fix those than add a check
that has implications on whether a program crashes or not.

**Comment by coryrc** [comment]
The error found in the application logs is:

2019/06/13 <time> internal.flushLog: Flush RPC: service bridge returned HTTP 400 ("App Engine APIs over the Service Bridge are disabled.\nIf they are required, enable them by setting the following to your app.yaml:\n\nbeta_settings:\n  enable_app_engine_apis: true\n")

Which is wildly confusing. Given the library used to support Flex and no longer does, I think verification is good because it just can't work.
