### ISSUE TITLE
Datastore package IN operator

### ISSUE THREAD

**Issue by tonto** [golang/appengine#24]
Why doesn’t `appengine/datastore` package have operator `IN` available when using `.Filter`

I see that python does

what difference does it make, it’s the same datastore ?!

**Comment by adamtanner** [comment]
NDB implements the `IN` operator client-side by creating an `OR` with multiple `==` conditions. Datastore does not natively support `IN`. For Go we've decided it's better to make that explicit rather than provide a utility function.
