### ISSUE TITLE
Log flushing error after every endpoint is called

### ISSUE THREAD

**Issue by benny-conn** [golang/appengine#266]
After registering handlers through the method described [here](https://pkg.go.dev/google.golang.org/appengine#Main) and using `appengine.Main()` in the main package, I notice that upon every request and small error is printed into the app engine logs regarding log flushing. The error is as below:

`internal.flushLog: Flush RPC: Call error 1: call /logservice.Flush is not registered`

The error does not prevent the application from working as intended but it is cluttering the logs and I am wondering if there is anything I can do on my end to fix this error.

Thanks ahead of time!

**Comment by munaita-0** [comment]
same problem. can't remove it.
