### ISSUE TITLE
Regression: `Metadata fetch failed` error during test run

### ISSUE THREAD

**Issue by manisenkov** [golang/appengine#27]
```
$ go test
...
2016/10/05 16:52:01 Metadata fetch failed: Get http://metadata/computeMetadata/v1/instance/attributes/gae_project: dial tcp: lookup metadata: no such host
exit status 1
```
This was introduced by commit https://github.com/golang/appengine/commit/926995697fa8241be2dc73eb318666e24f44ed51

**Comment by adamtanner** [comment]
@shantuo, can you take care of this?

**Comment by evanj** [comment]
In case it helps others who find this on the Internet: This can cause App Engine unit tests to hang. Reverting to commit 150dc57a1b (immediately previous) fixed the issue for me.
