### ISSUE TITLE
v2 unsupported API question

### ISSUE THREAD

**Issue by jschoedt** [golang/appengine#270]
Would it be possible to access the search feature (Search API) from a 2gen standard runtime? 
If so how would I go about doing that?

I am thinking either:
1. create an appengine.Context and use "v1" api in my code
2. port the v1 search api to v2
3. wait for google to add it

Thanks

**Comment by jschoedt** [comment]
I have tried to port the search API to v2 on this fork, but I keep getting `Call error 1: call /search.Search is not registered"`. So I am stuck on v1 and go 1.11 for now :-( 

https://github.com/jschoedt/appengine/tree/master/v2/search

**Comment by ludoch** [comment]
Search API is coming soon, a PR has been approved and will be merged very soon now.
