### ISSUE TITLE
Task queues stopped running

### ISSUE THREAD

**Issue by faisalraja** [golang/appengine#278]
Tasks are still added but it never executes anymore. I have tried default and true options for enable_task_running. I can sometimes make it work very rarely after several restarts and then after running a single task it never runs any new ones. Even after hitting run in the console it still doesn't execute. Thanks

Here are versions of what is installed:
Google Cloud SDK 377.0.0
app-engine-go 1.9.72
app-engine-python 1.9.99

**Comment by bsiegert** [comment]
Is this in `dev_appserver.py` or in prod?

If the former: Does the code change in #279 help with your problem?

**Comment by faisalraja** [comment]
@bsiegert This is for dev_appserver.py these are for both delay and taskqueue.NewPOSTTask then taskqueue.Add and the delay function. I did notice that error for the delay function but for direct taskqueue there's no error. Just doesn't get executed. Even after hitting "Run" in the admin console. After few stop/starts it can sometimes work once then won't work anymore after the first one.

**Comment by bsiegert** [comment]
I had exactly the same problem. See the patch in #279 and the App Engine SDK bug report liked from there.

**Comment by faisalraja** [comment]
@bsiegert I saw it, but it only touches the delay.go. Is this because once that error has been triggered the dev_appserver.py stops doing processes? I'm assuming it is based on your response. Thanks!

**Comment by sudhagarc** [comment]
I observe this issue (delay Function fails to execute) using appengine/v2 as well. Looks like @bsiegert is correct about gob vs base64 encoding, as POST to delay queue returns 500 (Internal server error). 

Has anyone found a workaround? Could we fix this please? Thanks.
