### ISSUE TITLE
Recursive deploy problem

### ISSUE THREAD

**Issue by lbhdc** [golang/appengine#294]
I am not positive this is the correct place to report this error, but it seems like the most relevant.

I ran into a strange problem today while trying to use deploy a go service to appengine using cloud build. Apparently the presence of `cloudbuild.yaml` changes the behavior of `gcloud app deploy`.

My cloud build looks like this.
```yaml
steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "app",
        "deploy",
    ]
``` 

My project has this structure
```
.
├── go.mod
├── go.sum
├── main.go
└── app.yaml
```

The app builds fine, but deploying it is when it gets strange. The deploy kicks off, but then it starts spawning dozens of cloud build jobs. They start to get deeply nested build logs like this.
```
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: e11f6dcc6c4f: Verifying Checksum
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: e11f6dcc6c4f: Download complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 005c982b9841: Verifying Checksum
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 005c982b9841: Download complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: a8ca11554fce: Verifying Checksum
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: a8ca11554fce: Download complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 9695e1422225: Verifying Checksum
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 9695e1422225: Download complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 8dcfed2e9b49: Verifying Checksum
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 8dcfed2e9b49: Download complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 1af13bf94a18: Verifying Checksum
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 1af13bf94a18: Download complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: f4fc807d1d80: Verifying Checksum
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: f4fc807d1d80: Download complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: a8ca11554fce: Pull complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 005c982b9841: Pull complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: e11f6dcc6c4f: Pull complete
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 3c20e68dca1a: Verifying Checksum
Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: Step #1: 3c20e68dca1a: Download complete
```

Removing cloud build all together solves the problem.

**Comment by jinglundong** [comment]
cloudbuild.yaml is not supported by `gcloud app deploy`. So, the short answer is: this is not a supported feature. 

I think there is a bug when we handle the `gcloud app deploy` request (likely on the server side), causing an infinite loop - `gcloud app deploy` try to call another `gcloud app deploy` again and again. 

It would be nice to reject this type of input or request. However, to be honest, it's very unlikely to be implemented unless we see more customers encounter the same issue. I'm going to resolve this issue for now. Please feel free to reopen if necessary.
