### ISSUE TITLE
Error handling ?

### ISSUE THREAD

**Issue by azr** [golang/appengine#36]
Howdy, I could not find anything on error handling.

How do you handle errors in there ? Are they typed ?

Thanks !

I'd like to avoid using things like :
```
if err.Error() == `API error 8 (images: OBJECT_NOT_FOUND)` {
```

But that error is of type `*internal.APIError` . . .

Can I help ?
Cheers !

**Comment by adamtanner** [comment]
Is there a specific error you're trying to check for? Can you share the bit of code that is failing with the opaque error?

**Comment by azr** [comment]
The specific code is:
```
	url, err := image.ServingURL(ctx, k, &image.ServingURLOptions{Secure: true})
	if err != nil {
		switch err.Error() {
		case `API error 8 (images: OBJECT_NOT_FOUND)`:
			rw.WriteHeader(http.StatusNotFound)
                ....
		default:
			rw.WriteHeader(http.StatusInternalServerError)
		}
		return
	}
```
This specific handler redirects to the serving url of a storage image.
But it's public, and I wanted to be able to differentiate between something wrong and between a 404 image.

Just looking at https://godoc.org/google.golang.org/appengine/image tells that there is no error handling possible nor any documentation on error handling

**Comment by Veejay** [comment]
We're noticing that OBJECT_NOT_FOUND error as well for a Golang app deployed on AppEngine.

The associated code is 

```golang
ctx := appengine.NewContext(r)
	
	objectName := fmt.Sprintf("%s", "/gs/"+bucketID+"/"+objectID)
	key, err := blobstore.BlobKeyForFile(ctx, objectName)
	if err != nil {
		log.Infof(ctx, "Couldn't generate BlobKeyForFile for resource %v with Error: %v", objectName, err)
		http.Error(w, "blobstore.BlobKeyForFile : "+err.Error(), http.StatusUnprocessableEntity)
	}
	res, err := image.ServingURL(ctx, appengine.BlobKey(key), &image.ServingURLOptions{Secure: true})
```

For every single case we've noticed in the logs for that error, the file actually exists in the bucket.

The error we're getting is:

```
Couldn't get serving_url for resource /gs/BUCKET_NAME/OBJECT_NAME with Error: API error 8 (images: OBJECT_NOT_FOUND)
```

**Comment by rbretecher-fcms** [comment]
Hello !

We're experiencing the same issue in our application. Did you manage to find any way to solve this issue ?

Thanks :)

**Comment by jschoedt** [comment]
Here is a link to the OBJECT_NOT_FOUND issue https://github.com/golang/appengine/issues/123
