### ISSUE TITLE
aetest.NewContext times out

### ISSUE THREAD

**Issue by slash-dev** [golang/appengine#49]
Hi,

I tried to run tests I created test and ran into issues with aetest timing out.

First my environment (I just redownloaded the last versions yesterday but had the problem before too):
$ goapp version
go version go1.6.3 (appengine-1.9.48) linux/amd64
$ go version
go version go1.7.5 linux/amd64

I started to write a dead simple "test" in a '$GOPATH/src/aetest_bug/model' directory:

```
package model

import (
	"appengine/aetest"
	"testing"
)

func TestFailing(t *testing.T) {
	aetest.NewContext(nil)
}
```

Now I try to run:
```
$ goapp test ./...
.... timeout. (never returns)

$ goapp test ./model
....timeout (never returns)

$ goapp test ./model/ -v
2017/02/03 17:00:43 appengine: not running under devappserver2; using some default configuration
=== RUN   TestFailing
...
.... DEBUG INFO...
...
--- PASS: TestFailing (0.50s)
PASS
ok  	aetest_bug/model	0.557s

$ goapp test ./... -v
.... timeout. (never returns)
```

This is very surprising. Knowing that if I remove any use of aetest but actually write tests instead, the 4 commands work perfectly. So just adding the verbose option makes it work but only if I specify the directory...

Also, interestingly, if I look at the code https://github.com/golang/appengine/blob/master/aetest/instance.go, I can't even find the same NewContext() function. All of them don't take any argument. How is that possible, is the version shipped in the package different from this one?

Any idea why this is happening?

Thanks!

**Comment by adamtanner** [comment]
I'd imagine it would leak a running devappserver, but it's interesting that it just hangs. I'll take a look.

The `appengine` packages shipped in the SDK are slightly different than the `google.golang.org/appengine` packages.

Most of the changes can be done automatically by `go get google.golang.org/appengine/cmd/aefix` and `aefix` and the others are documented in the README.

The `appengine` packages have been deprecated for a few years and all documentation should point to `google.golang.org/appengine` now. They continue to ship with the SDK to avoid breaking users.

**Comment by slash-dev** [comment]
Oh indeed. Now I migrated to the google.golang.com one and it works. Sorry about that. Thanks!
