### ISSUE TITLE
aetest: empty result query datastore

### ISSUE THREAD

**Issue by slash-dev** [golang/appengine#50]
Hi,

I'm trying to write tests for my website and I wanted to test my model. I ran into problems in my queries that only happened in the aetest testing environment but perfectly worked in the dev app server and in production. I found a minimal version of the code that has the bug that you can find here: https://drive.google.com/open?id=0B3x5qMnNZU0gUDNDemtxSG1fU1U

Long story short. When I use an aetest context with datastore, if I just do a datastore.Put() then datastore.Get(key), The object is saved and retrieved successfuly. Though if instead of doing a datastore.Get(key) I do a datastore.NewQuery(), then no result is returned.

I found a hack though, if between the datastore.Put() and the datastore.NewQuery() I add a basic datastore.Get(), now my query works perfectly :)

It sounds like there is a kind of Flush that is not done if I just call Put() but by calling Get(), it does it. Is that an expected behavior?

In case you can't access the link here are the code of the files in the archive:
$GOPATH/src/aetest_bug/model/user_test.go
```
package model

import (
	"appengine"
	"appengine/aetest"
	"testing"
)

func getContextAndSaveUser(t *testing.T) appengine.Context {
	ctx, err := aetest.NewContext(nil)
	if err != nil {
		t.Fatal(err)
	}
	// Create a user and save it in the database.
	user := &User{
		Email: "test@email.com",
	}
	if err := user.Save(ctx); err != nil {
		t.Fatal(err)
	}
	return ctx
}

func queryAllUsers(t *testing.T, ctx appengine.Context) {
	users, err := GetAllUsers(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(users) != 1 {
		t.Fatalf("Unexpected number of users, got %v", len(users))
	}
	if users[0].Email != "test@email.com" {
		t.Fatalf("Unexpected email, got %v", users[0].Email)
	}
}

func TestFailing(t *testing.T) {
	ctx := getContextAndSaveUser(t)
	// No hack, GetAllUsers() will work but won't find any user.
	// Get all the saved users.
	queryAllUsers(t, ctx)
}

func TestWorking(t *testing.T) {
	ctx := getContextAndSaveUser(t)
	// HACK HACK HACK: retrieve the user makes GetAllUsers() work.
	retrievedUser, err := GetUserFromEmail(ctx, "test@email.com")
	if err != nil {
		t.Fatal(err)
	}
	if retrievedUser.Email != "test@email.com" {
		t.Fatalf("Unexpected email, got %v", retrievedUser.Email)
	}
	// Get all the saved users.
	queryAllUsers(t, ctx)
}
```

$GOPATH/src/aetest_bug/model/user.go
```
package model

import (
	"appengine"
	"appengine/datastore"
)

const (
	UserKeyType = "UserKeyType"
)

type User struct {
	Key   *datastore.Key `datastore:"-"`
	Email string
}

func (user *User) Save(ctx appengine.Context) error {
	if user.Key == nil {
		user.Key = datastore.NewKey(ctx, UserKeyType,
			user.Email, 0, nil)
	}
	var err error
	user.Key, err = datastore.Put(ctx, user.Key, user)
	return err
}

func GetUserFromEmail(ctx appengine.Context, email string) (*User, error) {
	key := datastore.NewKey(ctx, UserKeyType, email, 0, nil)
	var user User
	if err := datastore.Get(ctx, key, &user); err != nil {
		return nil, err
	}
	user.Key = key
	return &user, nil
}

func GetAllUsers(ctx appengine.Context) ([]*User, error) {
	q := datastore.NewQuery(UserKeyType)
	users := make([]*User, 0, 0)

	for t := q.Run(ctx); ; {
		var user User
		k, err := t.Next(&user)
		if err == datastore.Done {
			break
		}
		if err != nil {
			return nil, err
		}
		user.Key = k
		users = append(users, &user)
	}
	return users, nil
}
```

**Comment by adamtanner** [comment]
This is expected behavior because queries (without an explicit ancestor) are eventually consistent. See the docs at https://cloud.google.com/appengine/docs/go/datastore/data-consistency for more information.

**Comment by slash-dev** [comment]
Hi,

I understand this in production. Though in testing environment, how can I write tests then? I saw that when we create an instance, we can pass the option "StronglyConsistentDatastore" but I can't see that with a simple NewContext(). Is there a way to do it? Or a better test practice?

Thanks!
