### ISSUE TITLE
download tool for appengine

### ISSUE THREAD

**Issue by gertcuykens** [golang/appengine#53]
https://godoc.org/golang.org/x/build/version/go1.8rc3

Can we have the same download sdk tool for appengine please, that put a appengine goroot in the same sdk directory?

Maybe name it go1.7app1

```
go get golang.org/x/build/version/go1.7app1
go1.7app1 download
```

**Comment by adams-sarah** [comment]
@cybrcodr @shantuo @sbuss

**Comment by shantuo** [comment]
App Engine Standard supports 1.6 and 1.8, both of which are installed with the app-engine-go components.

For App Engine Flexible, you shouldn't need tools other than the Go SDK.
