### ISSUE TITLE
Embedded structs no longer working

### ISSUE THREAD

**Issue by xStrom** [golang/appengine#54]
Having the following code:

```go
type ContainerStruct struct {
    embeddedStruct
}

type embeddedStruct struct {
    X int
}

cs := &ContainerStruct{}
cs.X = 5
```

Storing `cs` used to work just fine. I could save it to datastore, and fetch it back and `cs.X` would have the correct value. However this stopped working at some point.

This seems to be related to Go issue [#12367](https://github.com/golang/go/issues/12367). The issue says that Go 1.6 *will break packages like xml and json, but only minimally. The typical check for whether a field is exported, f.PkgPath != "", would have to be amended to f.PkgPath != "" && !f.Anonymous.*

Indeed, if I edit [datastore/prop.go](https://github.com/golang/appengine/blob/b8dd67741c75724e7c79d6ecd1266fe8f466f61d/datastore/prop.go#L203) to check `f.PkgPath != "" && !f.Anonymous` then my application code with embedded structs seems to be working again.

There doesn't seem to be any mention of this breaking change in the Go SDK release notes. So is this a bug that will be fixed, or do you consider it irrelevant luck that this used to work for years in the first place?

**Comment by adams-sarah** [comment]
Hey Kaur,
So I've tried reproducing this with many different commits, all the way back to 2e55c7f3ecff37664aace8565394fca6f16ecaab on Feb 20, 2015 and still I cannot. I see the same behavior as is currently present, where the embedded anonymous structs are ignored.

Do you have a commit SHA or even commit date-range when this worked for you?

I agree that this is probably not the ideal behavior anymore, but we cannot change it at this point b/c this is the behavior that went GA in July 2015.

We've at least fixed the behavior for the cloud.google.com/go/datastore package though, FYI (it does check `f.PkgPath != "" && !f.Anonymous`)

**Comment by xStrom** [comment]
I don't think this is a regression of this package in the classical sense where local code changes are the cause. I think this is due to a change in the core Go library `reflect` package. It's discussed in more detail in Go issue [#12367](https://github.com/golang/go/issues/12367) and was also highlighted in the [Go 1.6 release notes](https://golang.org/doc/go1.6#reflect).

Indeed I just tested with Go SDK 1.9.34 (`go version go1.4.2 (appengine-1.9.34) windows/amd64`) and the embedded structs in question still work there even with the latest `appengine` package from this repo. You'll notice that this SDK is from March 2016, which is in the GA period.

To be even more exact, it seems to me that the maintainers of the `appengine` package missed the memo in the Go 1.6 release notes that says *Code that walks data structures using reflection, especially to implement serialization in the spirit of the encoding/json and encoding/xml packages, may need to be updated.*

**Comment by adams-sarah** [comment]
Ah, I see. I will try to take a look at this soon.
Alternatively, if you have the time to submit a PR, I'd greatly appreciate :)

Thanks for pointing this out.

**Comment by xStrom** [comment]
I submitted that PR.
