### ISSUE TITLE
Support http.request.Context() and http.request.WithContext()

### ISSUE THREAD

**Issue by roseperrone** [golang/appengine#66]
net/http.Request.Context() was added in Go 1.7, yet when I use `api_version: go1.7` in my app.yaml, I still get this error:

`type *http.Request has no field or method Context`

**Comment by floresj** [comment]
Was this in the standard environment? If so, I think they're still on 1.6

**Comment by broady** [comment]
Correct, once we're on Go 1.7+, we should add this.

**Comment by warent** [comment]
This bug has caused much weeping and gnashing of teeth...

**Comment by broady** [comment]
Can't give an accurate timeline, sorry. Hoping for the order of a month or
two.

**Comment by zombiezen** [comment]
Marking fixed.
