### ISSUE TITLE
tests failing on CI

### ISSUE THREAD

**Issue by adams-sarah** [golang/appengine#71]
FAIL	google.golang.org/appengine/aetest [build failed]
FAIL	google.golang.org/appengine/remote_api [build failed]

https://travis-ci.org/golang/appengine/jobs/220643624

Since we're now accepting PRs here, it would be good to have CI working.

cc @adamtanner @broady @zombiezen

**Comment by broady** [comment]
The travis config is incorrect.

https://github.com/golang/appengine/pull/70/commits/d7022abe6b6fa42e7eab9800303695fc64b76b8a

**Comment by adams-sarah** [comment]
Awesome thx.

**Comment by broady** [comment]
https://github.com/golang/appengine/pull/72
