### ISSUE TITLE
goapp cmd get ImportError: cannot import name goroots

### ISSUE THREAD

**Issue by tjun** [golang/appengine#74]
Hi,

I updated gcloud command to ver.155.0.0.
After that, I got the following errors on `goapp test`

```
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/platform/google_appengine/goapp", line 13, in <module>
    from google.appengine.tools import goroots
ImportError: cannot import name goroots
```

I think the latest update for goroot specific cause this error.
How can I fix it?

**Comment by adams-sarah** [comment]
+ @sbuss @broady @zombiezen

**Comment by sbuss** [comment]
Thanks for the bug report. This is a known issue and we should be rolling out a fix next week in version 156. In the meantime, you can work around it via `echo "GOROOTS = {'go1': 'goroot', 'go1.6': 'goroot'}" > /opt/google-cloud-sdk/platform/google_appengine/google/appengine/tools/goroots.py`

**Comment by tjun2** [comment]
Thank you for your information 👍

**Comment by alanma** [comment]
Thanks. Waiting for gcloud v156...

**Comment by tjun** [comment]
Great! Thanks.

**Comment by sbuss** [comment]
@tjun The latest SDK should have fixed this, can you confirm please?

**Comment by tjun** [comment]
@sbuss Yes, I tried and it fixed! Thank you.

**Comment by raghuvanshy** [comment]
Found this error 
  ```
File "/opt/google-cloud-sdk/platform/google_appengine/goapp", line 40, in <module>
   from google.appengine.tools import goroots
ImportError: cannot import name goroots
```

My config:
```
Installation Root: [/opt/google-cloud-sdk]
Installed Components:
  core: [2018.02.12]
  app-engine-python: [1.9.66]
  app-engine-go: []
  beta: [2017.09.15]
  gsutil: [4.28]
  bq: [2.0.29]
```
Error when running dev_appserver.py app.yaml
```
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/bin/dev_appserver.py", line 11, in <module>
    import bootstrapping.bootstrapping as bootstrapping
  File "/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 9, in <module>
    import setup
ModuleNotFoundError: No module named 'setup'
```

I did your echo hack and the line exists in the file, any suggestions on how to proceed

**Comment by zombiezen** [comment]
@raghuvanshy Can you please open a new issue?

**Comment by sousk** [comment]
Hi all, 
I got the same problem so that I opened a new issue #124.
The Cloud SDK version is `190.0.1`. 
I'm glad if it will be a help.
