### ISSUE TITLE
aetest broken after Managed VMs beta environment deprecation

### ISSUE THREAD

**Issue by yi-jiayu** [golang/appengine#79]
The `app.yaml` template in https://github.com/golang/appengine/blob/master/aetest/instance_vm.go#L272 sets `vm: true`. However, after the Managed VMs beta environment deprecation and Google Cloud SDK 160.0.0, this option causes `dev_appserver.py` to print a deprecation notice and exists, while the `aetest` package is waiting for the child `dev_appserver.py` process to print its admin url (https://github.com/golang/appengine/blob/master/aetest/instance_vm.go#L233), and ultimately fails with a "timeout starting child process" error (https://github.com/golang/appengine/blob/master/aetest/instance_vm.go#L248), breaking tests relying on `aetest.NewContext()`. 

Since this repository is specifically for the App Engine standard environment and is not meant to support the flexible environment, is there a reason for `vm: true` being set in the `app.yaml` template? Removing that line seems to be a workaround for this issue.

**Comment by broady** [comment]
There's no reason to have that set. Feel free to send a pull request. We
should also add appropriate tests for this.

Thanks for the report!

**Comment by yi-jiayu** [comment]
I see, thanks for the clarification! I'm not sure how to write a test for this since it's dependent on `dev_appserver.py` and I'm not sure if that's the same in the `gcloud` SDK and the `goapp` one, but I'll send a PR removing the `vm: true` line.
