### ISSUE TITLE
Don't output panic error to HTTP response

### ISSUE THREAD

**Issue by dchenk** [golang/appengine#84]
There should be a way to prevent runtime panics from causing big, ugly HTTP responses with error traces to the client. For example, a small typo in an SQL query causes MySQL to throw an error, which makes the entire application panic and output the trace in the request handler.

Currently on App Engine Standard Environment, it's impossible to create a recovery wrapper function for the http.HandlerFunc because there's no access for us to `func main()`.

Here's an example of such a response to the browser when a runtime panic occurs:

the runtime process gave a bad HTTP response: ''

2017/08/09 23:56:51 ERROR:; Error 1146: Table 'table_name' doesn't exist
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x136139a]

goroutine 22 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
/Users/Username/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/database/sql/sql.go:2422 +0x7a
database/sql.(*Rows).Close(0x0, 0xc4201962c0, 0x1)
/Users/Username/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/database/sql/sql.go:2418 +0x3d
panic(0x1406b20, 0x16a0220)
/Users/Username/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/runtime/panic.go:489 +0x2cf
database/sql.(*Rows).Next(0x0, 0x14a40c0)
/Users/Username/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/database/sql/sql.go:2133 +0x30
main08084.listAllRows.func2(0x148ac1f, 0x1, 0x1494777, 0x19, 0x0, 0x0, 0x0, 0x0, 0xc4201962c0, 0x1, ...)
pagesposts.go:83 +0x1e1
created by main08084.listPagesOrPosts
pagesposts.go:97 +0x62a

**Comment by adams-sarah** [comment]
@dchenk you can recover inside your handlers.
(untested code)

```go
func myhandler(w http.ResponseWriter, r *http.Request) {
        defer func() {
            if r := recover(); r != nil {
                fmt.Println("Recovered in myhandler", r)
            }
        }()
        // do myhandler stuff
}
```
or if you need something more general

```go
func withRecover(fn http.HandlerFunc) http.HandlerFunc {
        return func(w http.ResponseWriter, r *http.Request) {
            defer func() {
                if r := recover(); r != nil {
                    fmt.Println("Recovered in myhandler", r)
                }
            }()
            fn(w,r)
        }
}
```
and then
```go
http.HandleFunc("/blah", withRecover(myHandler))
```

**Comment by adams-sarah** [comment]
On the other hand, the panic is a nil pointer dereference.
You should always be checking for `nil` before dereferencing (calling methods on or accessing data from) pointers.

**Comment by dchenk** [comment]
Hello @adams-sarah. Thanks for your response. It's true that I should be checking for `nil`, and I'm doing that everywhere now. However, the last time I tried wrapping my `func(ResponseWriter, *Request)` with a recovery `func` it was not working the way you suggest here. Can you maybe try it out yourself in Standard Environment (make a fatal error occur and recover this way)?

**Comment by derekperkins** [comment]
@dchenk You can definitely recover in GAE, in fact the GAE wrapper code has (or at least had previously) a panic recovery built in. My guess is that you are running your db request in a goroutine. `defer ... recover` only works inside the current stack.
