### ISSUE TITLE
aetest: Can't assume that request pointer doens't change (go 1.7)

### ISSUE THREAD

**Issue by fredr** [golang/appengine#85]
In `aetest` it is assumed that the request pointer remains the same during a request:
https://github.com/golang/appengine/blob/d9a072cfa7b9736e44311ef77b3e09d804bfa599/aetest/instance_vm.go#L73
https://github.com/golang/appengine/blob/eda0abe86b8018c6924fac5f669c9f52eb0c68b8/internal/api.go#L258

In go 1.7 when doing a `req.WithContext` an new request pointer is returned that points to a copy of the request, with new context. This is an issue when i.e using Gorilla mux, since this native context patch:
https://github.com/gorilla/mux/commit/fdfca9f9173962ed22bc63adc02a1589e43c1405#diff-b303fad270323289aeb17e2f0930ffa7

But I assume this is a problem with all go 1.7 apps that uses a `req.WithContext` to update the context: https://golang.org/src/net/http/request.go?h=WithContext#L327

(This causes a "appengine: NewContext passed an unknown http.Request" error, since it can't find an associated context with the request)

**Comment by adams-sarah** [comment]
@broady FYI

**Comment by broady** [comment]
This will be fixed in the next release of the App Engine SDK. Sorry, it's taking a while.

https://groups.google.com/forum/#!topic/google-appengine-go/Av7Lg956D6Y
https://groups.google.com/forum/#!topic/google-appengine-go/EDNAnEp4VpI

**Comment by katiemthom** [comment]
@broady When do you estimate that release will be?

**Comment by broady** [comment]
Should have happened already. Can you try again?

**Comment by haroldcampbell** [comment]
@broady is there any update on this bug?

**Comment by katiemthom** [comment]
I'm also interested in an estimate as to when this will be resolved.

**Comment by mvpmvh** [comment]
commenting in order to receive github notifications

**Comment by astec** [comment]
@mvpmvh there is a nice "Subscribe" button for that purpose.

**Comment by schmorrison** [comment]
Curious if there have been any updates?

Handlers that were working fine yesterday suddenly started throwing this error: 
`panic: appengine: NewContext passed an unknown http.Request`

I am using gorilla/mux but it wasn't a problem prior to this morning.

There really doesn't seem to be any suggestions about working around it.

Thanks,

Sam Morrison

**Comment by zombiezen** [comment]
Marking fixed
