### ISSUE TITLE
remote_api: NewRemoteContext is expensive

### ISSUE THREAD

**Issue by zombiezen** [golang/appengine#86]
`NewRemoteContext` makes an HTTP request on every call.  In scenarios where a request needs to inherit values from another parent context, it would be better to have one `NewClient` function that can be established process-wide, and then have a `Client.NewContext(parent context.Context)` method that can be run cheaply.

**Comment by broady** [comment]
Note that the docs indicate this, but could be more explicit:

```
NewContext starts an instance of the development API server, and returns a context that will route all API calls to that server, as well as a closure that must be called when the Context is no longer required.
```

**Comment by zombiezen** [comment]
I'm suggesting a backward-compatible change, not a breaking one.  See https://go-review.googlesource.com/57730 for background.

Imagine if you were to use remote API in a non-App Engine server and you want to have a context that includes both your current request's information/cancel/deadline and the remote API's values.  The end-developer has to create a custom Context type to merge the two contexts, and likely wasting a goroutine in the process.

What I'm proposing is this:

```go
// A Client can create remote API contexts.
// Implementation detail: this is just remoteContext exported.
type Client struct {
	client *http.Client
	url    string
	appID  string
}

// NewClient connects to the remote API and returns a new Client.
func NewClient(host string, client *http.Client) (*Client, error) {
  // ... do most everything that NewRemoteContext is doing now ...
  return &Client{client, u, appID}
}

// NewContext returns a context that gives access to the production
// App Engine APIs for the application at the given host.
func (c *Client) NewContext(parent context.Context) context.Context {
	ctx := internal.WithCallOverride(parent, c.call)
	ctx = internal.WithLogOverride(ctx, c.logf)
	ctx = internal.WithAppIDOverride(ctx, appID)
	return ctx
}

// NewRemoteContext ...
func NewRemoteContext(host string, client *http.Client) (context.Context, error) {
	c, err := NewClient(host, client)
	if err != nil {
		return nil, err
	}
	return c.NewContext(context.Background()), nil
}
```
