### ISSUE TITLE
delay package is not working.

### ISSUE THREAD

**Issue by koba-ninkigumi** [golang/appengine#89]
Old Package "appengine/delay" is good for me.
But "google.golang.org/appengine/delay" is not working.
Error log is "delay: func is invalid: first argument must be context.Context".

Now, I changed line 115 of "google.golang.org/appengine/delay".

-----
    - if t.NumIn() == 0 || t.In(0) != contextType {
    + if t.NumIn() == 0 || fmt.Sprint(t.In(0)) != fmt.Sprint(contextType) || reflect.TypeOf(t.In(0)) != reflect.TypeOf(contextType) {
-----
This solution is good for me.

What do you think?
Thanks.

**Comment by broady** [comment]
Doesn't seems nice, to me.

What is your code? Are you using "context" or "golang.org/x/net/context"?

**Comment by koba-ninkigumi** [comment]
@broady Thanks nice advice!
After changing "context" to "golang.org/x/net/context", it works well! 
Thanks!

    package main

    import (
    - "context"
    + "golang.org/x/net/context"
      "fmt"
      "html/template"
      "io"
      "net/http"
      "strconv"

      "google.golang.org/appengine"
      "google.golang.org/appengine/delay"
      "google.golang.org/appengine/log"
      "google.golang.org/appengine/user"
    )

    func handler(w http.ResponseWriter, r *http.Request) {
      m := map[string]interface{}{
      "name":  "jack",
      "email": "example@example.com",
      }
      c := appengine.NewContext(r)
      err := laterFunc.Call(c, m)
      if err != nil {
        log.Errorf(c, "%v", err)
      }
      fmt.Fprint(w, "")
    }

    func asyncFunc(c context.Context, m map[string]interface{}) {
      log.Infof(c, "%v", m)
    }

    var laterFunc = delay.Func("post", asyncFunc)

    func init() {
      http.HandleFunc("/post", handler)
    }
