### ISSUE TITLE
Why I need to pass a context for everything in datastore package?

### ISSUE THREAD

**Issue by mrwnmonm** [golang/appengine#93]
What the purpose of passing the context to all functions in the datastore package other than canceling the request if something fails?

I want to make a layer above the package to make things easier, and I don't want to pass the request or calling `appengine.NewContext` every time. so I will just pass `context.Context` to all the functions from that layer. can I do that? what I will lose if I did that?

**Comment by astec** [comment]
@mrwnmonm, please close this issue as this tracker is for bugs & feature request.

This kind of questions is better ask in https://groups.google.com/forum/#!forum/google-appengine-go
