### ISSUE TITLE
Context not wrapped with appengine.Context will just panic with a `nil pointer` alert.

### ISSUE THREAD

**Issue by timakin** [golang/appengine#96]
When I use http.Request.Context, that was not wrapped with appengine.Context, it panicked.

The panic says `runtime error: invalid memory address or nil pointer dereference`.
But it's too ambiguous.

```
net/http.(*conn).serve.func1(0xc4202da780)
    /Users/name/go_appengine/goroot-1.8/src/net/http/server.go:1721 +0xd0
panic(0x14fe600, 0x1839db0)
    /Users/name/go_appengine/goroot-1.8/src/runtime/panic.go:489 +0x2cf
google.golang.org/appengine/internal.logf(0x0, 0x0, 0x1, 0xc4203be000, 0x81d8, 0x0, 0x0, 0x0)
    /Users/name/go/src/github.com/timakin/project/vendor/google.golang.org/appengine/internal/api_classic.go:147 +0x11c
google.golang.org/appengine/internal.Logf(0x1b7e000, 0xc420257aa0, 0x1, 0xc4203be000, 0x81d8, 0x0, 0x0, 0x0)
    /Users/name/go/src/github.com/timakin/project/vendor/google.golang.org/appengine/internal/api_common.go:80 +0x12e
google.golang.org/appengine/log.Infof(0x1b7e000, 0xc420257aa0, 0xc4203be000, 0x81d8, 0x0, 0x0, 0x0)
    /Users/name/go/src/github.com/timakin/project/vendor/google.golang.org/appengine/log/api.go:24 +0x73
g
```

I've prepared logger to print the inside of objects, but the logger also panicked because the context passed for the first arguement of `func Infof(ctx context.Context, format string, args ...interface{})` was not `appengine.Context`. 

So until I check the code of `google.golang.org/appengine/internal`, I could't know what happened.

It should raise an error which will tell you that you must use `context.Context` with `appengine.Context` to enable appengine to cast it in the internal packages.

**Comment by timakin** [comment]
In short I say more APIs should return this error.

https://github.com/golang/appengine/blob/eda0abe86b8018c6924fac5f669c9f52eb0c68b8/internal/api_common.go#L15

**Comment by kevinburke** [comment]
Not sure why this was closed, it seems like at the very least you could have a good error message here.

The godoc also specifies that golang.org/x/net/context is the Context you are supposed to pass in.
