### ISSUE TITLE
datastore: add omitempty support for time.Time

### ISSUE THREAD

**Issue by escholtz** [golang/appengine#98]
Would it be feasible to use [func (t Time) IsZero() bool](https://golang.org/pkg/time/#Time.IsZero) to support the `omitempty` struct tag for `time.Time` properties?

**Comment by adams-sarah** [comment]
hey, which package are you referring to? datastore?

**Comment by escholtz** [comment]
Yes, I'm referring to the datastore package.

**Comment by adams-sarah** [comment]
Hey, I'd gladly review a pull request :)

Here is the commit which adds omitempty functionality to cloud.google.com/go/datastore, which is almost identical in implementation to this package's datastore client. Might be helpful:
https://code-review.googlesource.com/c/gocloud/+/9670

**Comment by escholtz** [comment]
@adams-sarah I hope you're as excited about this PR as I am! If my calculations are correct, we're looking at 1.34 nano-dollars ($0.00000000134) in savings per zero Time per month. And that doesn't even include indices!

**Comment by astec** [comment]
@adams-sarah any chance we can get this anytime soon? I'm really looking forward to this feature.
